[loggers]
keys=root

[logger_root]
handlers=screen,file

[formatters]
keys=simple,complex

[formatter_simple]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s

[formatter_complex]
format=%(asctime)s - %(name)s - %(levelname)s - %(module)s : %(lineno)d - %(message)s

[handlers]
keys=file,screen

[handler_file]
class=handlers.TimedRotatingFileHandler
interval=midnight
backupCount=5
formatter=complex
level=DEBUG
args=('logs/vkscraper.log',)

[handler_screen]
class=StreamHandler
formatter=simple
level=INFO
args=(sys.stdout,)
WARNING:fake_useragent:Error occurred during formatting data. Trying to use fallback server https://fake-useragent.herokuapp.com/browsers/0.1.4
Traceback (most recent call last):
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 127, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 90, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE.format(browser=quote_plus(browser)))
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 54, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
FakeUserAgentError: Maximum amount of retries reached
WARNING:fake_useragent:Error occurred during formatting data. Trying to use fallback server https://fake-useragent.herokuapp.com/browsers/0.1.4
Traceback (most recent call last):
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 127, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 90, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE.format(browser=quote_plus(browser)))
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 54, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
FakeUserAgentError: Maximum amount of retries reached
WARNING:fake_useragent:Error occurred during formatting data. Trying to use fallback server https://fake-useragent.herokuapp.com/browsers/0.1.4
Traceback (most recent call last):
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 127, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 90, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE.format(browser=quote_plus(browser)))
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 54, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
FakeUserAgentError: Maximum amount of retries reached
WARNING:fake_useragent:Error occurred during formatting data. Trying to use fallback server https://fake-useragent.herokuapp.com/browsers/0.1.4
Traceback (most recent call last):
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 127, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 90, in get_browser_versions
    html = get(settings.BROWSER_BASE_PAGE.format(browser=quote_plus(browser)))
  File "/home/bogdan/Projects/vkscraper/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 54, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
FakeUserAgentError: Maximum amount of retries reached
